import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
//components
import Header from "../components/ui/Header";
import PageTransition from "../components/ui/PageTransition";
import StarirTransition from "@/components/ui/StairTransition";


// Configure the font using the correct options
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],  // Subsets should be an array
  variable: "--font-jetbrains-mono", // Custom CSS variable for the font
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"], // Weights as an array
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} font-sans antialiased`}>
        <Header />
        <StarirTransition />
        <PageTransition >
        {children}
        </PageTransition>
        
      </body> 
    </html>
  );
}
 